# Generated by Django 5.0 on 2023-12-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderhistory',
            old_name='unique_order_id',
            new_name='order_id',
        ),
    ]
