# Generated by Django 5.0 on 2023-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartSumaary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
