# Generated by Django 5.0 on 2023-12-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_records',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
