# Generated by Django 5.0 on 2023-12-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cartsumaary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.DeleteModel(
            name='cartSumaary',
        ),
    ]
