# Generated by Django 5.0 on 2023-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_orderamount_delete_cartsumaary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
    ]
