# Generated by Django 5.0 on 2023-12-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_invoice_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_document',
        ),
    ]
