# Generated by Django 5.0 on 2023-12-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_invoice_pdf_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.CharField(default='R0.00', max_length=255),
        ),
    ]
